### ISSUE TITLE
navigation for admin panel

### ISSUE THREAD

**Issue by cwsyth** [amplimindcc/frontend#17]
Eine Art von Navigation zwischen der Usermang. & Projectmang. Seiten ist notwendig. Umsetzung offen, beispielsweise Navigationbar oder eine Art Admin Start page (besser).

Admin Start Page würde anzeigen:

- Willkommenstext (ähnlich zu user Willkommensseite -> siehe issue)
- Name des Admins
- Zwei Links zu den gennanten Seiten

**Comment by MysterionAutotronic** [comment]
duplicate

**Comment by MysterionAutotronic** [comment]
duplicate
