### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by MysterionAutotronic** [amplimindcc/frontend#178]
Add Translation feature
- <a href="https://react.i18next.com/">react-i18next</a>
- switch language button in navbar

**Comment by ImpyKid** [comment]
DropDown-Menü mit Sprachen zur Auswahl
i18-Datei in Deutsch und Englisch
DropDown-Menü Sprachen reicht in Hardcode

**Comment by MysterionAutotronic** [comment]
Dropdown u.U. mit Icons (Flaggen)

**Comment by ImpyKid** [comment]
> Dropdown u.U. mit Icons (Flaggen)

Hätte ich eh geplant gehabt. en-US am besten, oder?

**Comment by MysterionAutotronic** [comment]
ja - alternativ kannst du auch Arbeit einsparen und das Browser Locale grabben
